function(copy_to_build FILE)
    set(FILE_COPY_FROM_FILE "${FILE}")
    get_filename_component(F ${FILE} NAME)
    set(FILE_COPY_TO_FILE "${CMAKE_CURRENT_BINARY_DIR}/${FILE}")
    configure_file(${FILE_COPY_FROM_FILE} ${FILE_COPY_TO_FILE} COPYONLY)
endfunction()
